# Generated by Django 4.1.7 on 2023-04-05 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_image_alter_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletype',
            name='sub_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shopping.subcategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='master_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shopping.mastercategory'),
            preserve_default=False,
        ),
    ]
