# Generated by Django 4.1.7 on 2023-04-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_articletype_sub_category_subcategory_master_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.FloatField(default=5.0),
            preserve_default=False,
        ),
    ]
